# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-01-19 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField(unique=True)),
                ('is_alive', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='urls',
            field=models.ManyToManyField(to='pdf_tool.Url'),
        ),
    ]
